### ISSUE TITLE
Exclude option

### ISSUE THREAD

**Issue by sidati** [MohammadYounes/grunt-rtlcss#3]
Salamu Alaykum,

Can you please add exclude option ?
Thank you for such tool it as very helpful :+1:

**Comment by MohammadYounes** [comment]
Wa Alaikum Salaam,

What do you mean by exclude option ?

**Comment by sidati** [comment]
I mean option to exclude some files when we use the -d option cial CLI, such as reset.css and stye.rtl.css, because from the CLI :
style.css => style.rtl.css

and execute it second time will generate :
style.css => style.rtl.css
style.rtl.css => style.rtl.rtl.css

P.S. I'm using a windows batch file instead of grunt/gulp.

**Comment by MohammadYounes** [comment]
Are you referring to [RTLCSS CLI](https://github.com/MohammadYounes/rtlcss/blob/master/docs/CLI.md)? Because this is repo is for the grunt plugin.

**Comment by sidati** [comment]
Yes, Sorry about that, i'll open another ticket there :)
